### Create a report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"Toyota",
    "model":"corola",
    "year": 2001,
    "lng": 20,
    "lat": 76,
    "mileage": 99000,
    "price": 100
}


### Approve a report
PATCH http://localhost:3000/reports/9
content-type: application/json

{
    "approved": true
}

### get estimate
GET http://localhost:3000/reports?make=Toyota&model=corola&year=2004&lng=15&lat=76&mileage=100000