### Create a report
POST http://localhost:3000/reports
Content-Type: application/json

{
    "make":"Mercedes",
    "model":"corola",
    "year": 2001,
    "lnt": 0,
    "lat": 0,
    "mileage": 100000,
    "price": 20000
}


### Approve a report
PATCH http://localhost:3000/reports/9
content-type: application/json

{
    "approved": true
}