POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "hedi@gmail.com",
    "password": "azerty123"
}

### Sign in
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "hedi@gmail.com",
    "password": "azerty123"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/1

### Find all users have a particular email
GET http://localhost:3000/auth?email=abc1@fd.com

### Remove a particular user with a given ID
DELETE http://localhost:3000/auth/12

### Update a user
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email": "salah@gmail.com"
}